# Generated by Django 3.2.20 on 2023-08-13 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('picture', models.ImageField(upload_to='images')),
                ('picture_width', models.IntegerField()),
                ('picture_height', models.IntegerField()),
                ('no_channel', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('pdf_document', models.FileField(upload_to='documents')),
                ('page_count', models.IntegerField()),
                ('page_width', models.IntegerField()),
                ('page_height', models.IntegerField()),
            ],
        ),
    ]
