# Generated by Django 3.2.20 on 2023-08-13 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_processing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='no_channel',
            field=models.CharField(max_length=50),
        ),
    ]
